### ISSUE TITLE
returned with exit code 1 Windows 10 pro

### ISSUE THREAD

**Issue by imakealol** [megadose/phoneinfoga-maltego#1]
Hello. I have the following problem. to bring I try PhoneInfoga for Maltego 4.2.16 CE to run, but I always get the error message "returned with exit code 1" to holehe in contrast. That works for me without further ado. What I can not understand is why this does not work, I did not do anything else like holehe.

EDIT: 

Der Befehl "killall" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Das System kann den angegebenen Pfad nicht finden.
Traceback (most recent call last):
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1008, in _send_output
    self.send(msg)
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 948, in send
    self.connect()
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 187, in connect
    conn = self._new_conn()
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001F9960208B0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/numbers/Entity%20Value/scan/numverify (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9960208B0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\phoneinfoga-maltego\phoneinfoga-maltego.py", line 49, in <module>
    numverify()
  File "C:\phoneinfoga-maltego\phoneinfoga-maltego.py", line 13, in numverify
    response = requests.get('http://127.0.0.1:5000/api/numbers/'+num+'/scan/numverify')
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\***** ****\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/numbers/Entity%20Value/scan/numverify (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9960208B0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte'))

**Comment by imakealol** [comment]
I solved the problem by running "C: \ phoneinfoga-maltego \ phoneinfoga.exe" serve. Now all that's left is the error message that the cannot find the killall command. I noticed that he does not accept mobile phone numbers because he keeps giving me the error message "Invalid phone number"

**Comment by megadose** [comment]
It's only for Windows sorry
